### ISSUE TITLE
Library has a global, non-namespaced dependancy on jsonlab

### ISSUE THREAD

**Issue by eoinmurray** [rinocloud/rinocloud-matlab#15]
The library does not work at all if someone has not installed jsonlab as a MATLAB toolbox (which is only supported from 2014 onwards). 

So that means that MATLAB 2013 and below cannot use rinocloud-matlab at all.

We need to either:

1. The dependancy needs to be installed by the user and correctly namespaced by us in the code. 
2. Or we need to package jsonlab up with rinocloud.

I would go with option 2. But it needs a substantial correction to the library as is: 

Examples of un-defined functions:

https://github.com/rinocloud/rinocloud-matlab/blob/master/%2Brino/savejson.m#L105

https://github.com/rinocloud/rinocloud-matlab/blob/master/%2Brino/loadjson.m#L93

**Comment by jamie47** [comment]
Fixed in bugfixes branch
